### ISSUE TITLE
process dies

### ISSUE THREAD

**Issue by kelson42** [openzim/kalite#6]
```
kalite manage export2zim /data/ka-fr.zim --language=fr --tmp-dir=/data/ka-lite-zim_fr --download
```
...
```
  INFO     | Let's try and fetch http://kalite.learningequality.org/download/videos/aNqG4ChKShI.mp4/aNqG4ChKShI.mp4
  INFO     | Videos processed: 108
  INFO     | Video file being downloaded to: /root/.kalite/content/b22tMEc6Kko.mp4
  INFO     | Let's try and fetch http://kalite.learningequality.org/download/videos/b22tMEc6Kko.mp4/b22tMEc6Kko.mp4
  INFO     | Videos processed: 109
  INFO     | Video file being downloaded to: /root/.kalite/content/incKJchBCLo.mp4
  INFO     | Let's try and fetch http://kalite.learningequality.org/download/videos/incKJchBCLo.mp4/incKJchBCLo.mp4
  INFO     | Videos processed: 110
  INFO     | Videos processed: 111
  INFO     | Video file being downloaded to: /root/.kalite/content/Wm0zq-NqEFs.mp4
  INFO     | Let's try and fetch http://kalite.learningequality.org/download/videos/Wm0zq-NqEFs.mp4/Wm0zq-NqEFs.mp4
  INFO     | Videos processed: 112
  INFO     | Video file being downloaded to: /root/.kalite/content/O9zSHs1TWMM.mp4
  INFO     | Let's try and fetch http://kalite.learningequality.org/download/videos/O9zSHs1TWMM.mp4/O9zSHs1TWMM.mp4
  INFO     | Videos processed: 113
  INFO     | Video file being downloaded to: /root/.kalite/content/9hM32lsQ4aI.mp4
  INFO     | Let's try and fetch http://kalite.learningequality.org/download/videos/9hM32lsQ4aI.mp4/9hM32lsQ4aI.mp4
  INFO     | Videos processed: 114
  INFO     | Video file being downloaded to: /root/.kalite/content/fOXo4p4WDKM.mp4
  INFO     | Let's try and fetch http://kalite.learningequality.org/download/videos/fOXo4p4WDKM.mp4/fOXo4p4WDKM.mp4
  INFO     | Videos processed: 115
Traceback (most recent call last):
  File "/usr/share/kalite/python-packages/django/core/management/base.py", line 224, in run_from_argv
    self.execute(*args, **options.__dict__)
  File "/usr/share/kalite/python-packages/django/core/management/base.py", line 263, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python2.7/dist-packages/kalite_zim/management/commands/export2zim.py", line 429, in handle
    copy_media(topic_tree)
  File "/usr/local/lib/python2.7/dist-packages/kalite_zim/management/commands/export2zim.py", line 390, in copy_media
    copy_media(child)
  File "/usr/local/lib/python2.7/dist-packages/kalite_zim/management/commands/export2zim.py", line 390, in copy_media
    copy_media(child)
  File "/usr/local/lib/python2.7/dist-packages/kalite_zim/management/commands/export2zim.py", line 390, in copy_media
    copy_media(child)
  File "/usr/local/lib/python2.7/dist-packages/kalite_zim/management/commands/export2zim.py", line 390, in copy_media
    copy_media(child)
  File "/usr/local/lib/python2.7/dist-packages/kalite_zim/management/commands/export2zim.py", line 390, in copy_media
    copy_media(child)
  File "/usr/local/lib/python2.7/dist-packages/kalite_zim/management/commands/export2zim.py", line 329, in copy_media
    copy_file(video_file_src, video_file_dest)
  File "/usr/local/lib/python2.7/dist-packages/kalite_zim/management/commands/export2zim.py", line 75, in copy_file
    soft_link(COPIED_FILES.get(src), dst)
  File "/usr/local/lib/python2.7/dist-packages/kalite_zim/management/commands/export2zim.py", line 57, in soft_link
    return os.symlink(src, dst)
OSError: [Errno 17] File exists
```

**Comment by dattaz** [comment]
This append when kalite dir ($HOME/.kalite) and tmp-dir are not in the same device, for example when mounting a device and using kalite in docker.
