### ISSUE TITLE
Few problems by downloading

### ISSUE THREAD

**Issue by kelson42** [openzim/kalite#7]
Even if most of the videos seem to be downloaded properly, the script seems to be blocked here:
```
  INFO     | Let's try and fetch http://kalite.learningequality.org/download/videos/01crUV4VSkk.mp4/01crUV4VSkk.mp4
  WARNING  | Download failed, retrying again in 2 seconds.
  ERROR    | Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/kalite_zim/utils.py", line 60, in download_video
    __, response = urllib.urlretrieve(url, video_filename)
  File "/usr/lib/python2.7/urllib.py", line 98, in urlretrieve
    return opener.retrieve(url, filename, reporthook, data)
  File "/usr/lib/python2.7/urllib.py", line 245, in retrieve
    fp = self.open(url, data)
  File "/usr/lib/python2.7/urllib.py", line 213, in open
    return getattr(self, name)(url)
  File "/usr/lib/python2.7/urllib.py", line 351, in open_http
    errcode, errmsg, headers = h.getreply()
  File "/usr/lib/python2.7/httplib.py", line 1196, in getreply
    response = self._conn.getresponse()
  File "/usr/lib/python2.7/httplib.py", line 1121, in getresponse
    response.begin()
  File "/usr/lib/python2.7/httplib.py", line 438, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python2.7/httplib.py", line 394, in _read_status
    line = self.fp.readline(_MAXLINE + 1)
  File "/usr/lib/python2.7/socket.py", line 480, in readline
    data = self._sock.recv(self._rbufsize)
IOError: [Errno socket error] timed out

  INFO     | Let's try and fetch http://kalite.learningequality.org/download/videos/01crUV4VSkk.mp4/01crUV4VSkk.mp4
  WARNING  | Download failed, retrying again in 2 seconds.
  ERROR    | Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/kalite_zim/utils.py", line 60, in download_video
    __, response = urllib.urlretrieve(url, video_filename)
  File "/usr/lib/python2.7/urllib.py", line 98, in urlretrieve
    return opener.retrieve(url, filename, reporthook, data)
  File "/usr/lib/python2.7/urllib.py", line 245, in retrieve
    fp = self.open(url, data)
  File "/usr/lib/python2.7/urllib.py", line 213, in open
    return getattr(self, name)(url)
  File "/usr/lib/python2.7/urllib.py", line 351, in open_http
    errcode, errmsg, headers = h.getreply()
  File "/usr/lib/python2.7/httplib.py", line 1196, in getreply
    response = self._conn.getresponse()
  File "/usr/lib/python2.7/httplib.py", line 1121, in getresponse
    response.begin()
  File "/usr/lib/python2.7/httplib.py", line 438, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python2.7/httplib.py", line 394, in _read_status
    line = self.fp.readline(_MAXLINE + 1)
  File "/usr/lib/python2.7/socket.py", line 480, in readline
    data = self._sock.recv(self._rbufsize)
IOError: [Errno socket error] timed out

```

**Comment by kelson42** [comment]
Effort discontinued, see `README.md`
